name: Transpile
on: deployment # Just never trigger
jobs: 
  transpile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3

      - run: npm ci

      - run: node_modules/.bin/tsc -p .

      - run: node out/piggify/piggify.js

      - uses: actions/upload-artifact@v3
        with:
          name: piggified
          path: piggify/piggy.zip

      - uses: actions/upload-artifact@v3
        with:
          name: transpiled
          path: out