name: Transpile

on: 
  workflow-dispatch: []
  release:
    type: published

jobs: 
  transpile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3

      - run: npm ci

      - run: node_modules/.bin/tsc -p .

      - run: node out/piggify/piggify.js

      - uses: actions/upload-artifact@v3
        with:
          name: piggified
          path: piggify/piggy.zip

      - uses: actions/upload-artifact@v3
        with:
          name: transpiled
          path: out

      - uses: svenstaro/upload-release-action@v2
        if: ${{ github.event.action }} == "published"
        with:
          asset_name: piggified.zip
          file: piggify/piggy.zip

      - run: sh -c "cd out && zip -r transpiled.zip . && mv transpiled.zip .." 

      - uses: svenstaro/upload-release-action@v2
        if: ${{ github.event.action }} == "published"
        with:
          asset_name: transpiled.zip
          file: transpiled.zip